name: CI

on:
  push:
    branches: [ master ]

jobs:
  build_and_test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Build project
      run: cargo build --release

    - name: Run tests
      run: cargo test --release

